apiVersion: lux.latere.ai/v1beta1
kind: Model
metadata:
  name: moonshot/moonshot-v1-128k
spec:
  targets:
    - provider: moonshot
      model: moonshot-v1-128k
      weight: 100
      priority: 0
  fallback: never
  pricing:
    currency: USD
    per: 1000000
    input: "2"
    output: "5"
