apiVersion: lux.latere.ai/v1beta1
kind: Model
metadata:
  name: openai/gpt-4o-mini
spec:
  targets:
    - provider: openai
      model: gpt-4o-mini
      weight: 100
      priority: 0
  fallback: never
  pricing:
    currency: USD
    per: 1000000
    input: "0.15"
    output: "0.6"
    cachedInput: "0.075"
