apiVersion: lux.latere.ai/v1beta1
kind: Model
metadata:
  name: zhipu/glm-4.5v
spec:
  targets:
    - provider: zhipu
      model: glm-4.5v
      weight: 100
      priority: 0
  fallback: never
  pricing:
    currency: USD
    per: 1000000
    input: "0.6"
    output: "1.8"
    cachedInput: "0.11"
